---
title: "P8105 -- Homework 5"
author: "Ngoc Duong -- nqd2000 "
date: "11/6/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r message = FALSE, warning = FALSE}
library(readr)
library(tidyverse)
library(ggplot2)
library(purrr)
```

## Problem 1
```{r}
#get dataset with missing values 
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()
```

```{r}
# write a function that follows set rules 
rep_func = function(x){                #start function taking column x as argument
  if (is.numeric(x)) {                 #set condition if x is numeric then...
    replace(x,                         #replace in column x...
            is.na(x),                  #values that are NA...
            round(                     #with the average of the other observations that are non NA's
              mean(x, na.rm = TRUE),
              2))
    }
 else if (is.character(x)) {           #set condition if column x is character then...
              replace(x,               #replace in column x...
                      is.na(x),        #values that are NAs...
                      "virginica")     #with "virginica"
}}

iris_imputed = map_df(iris_with_missing, rep_func)  #"map" the function on iris_with_missing using map_df
```

After replacing missing values according to the set rules, a glimpse at the "filled-in" dataset:
```{r}
head(iris_imputed, 10)
```


## Problem 2
```{r, warning = FALSE, message = FALSE}
# iterate over file names and read in data for each subject using purrr::map and saving the result as a new variable in the dataframe
file.list =
  tibble(path = list.files(path = "./data",     #use list.files to list all csv file names in data folder
                           pattern="*.csv", 
                           full.names = TRUE))

patient_data =
  file.list %>% 
  mutate(data = map(path, read_csv)) %>%        #use map to apply read_csv to read all file names in (as list), and assign those to column data
  unnest()                                      #unnest list  
```


Now we tidy the dataframe: break file names (path) down into arm and subject ID, tidy weekly observations, and do any other tidying that’s necessary
```{r}
patient_data_clean = 
patient_data %>% 
  extract(path,                                         #break path character variable down
          regex = "^(.*?)/(.*?)/(.*?)_(.*?)\\.(.*?)$",  #using regular expression specifying "/", "_", and "." as separators
          into = c("A","B","arm", "id", "C")) %>%       #separate into smaller components (some are necessary info; some aren't)
          pivot_longer(
             week_1:week_8,                             #make df longer 
             names_to = "week",                         #collapse 8 week columns into one week column
             values_to = "observation") %>%             #corresponding observations go to variable value
          separate(week, into = c("a","week"), sep = "_") %>% #get the number of week from week column
          mutate(id = factor(id),                       #make factor id and week 
                 week = factor(week),
                 arm =                                  #recode arm variable
                   recode(arm,
                          "con" = "control",
                          "exp" = "experimental")) %>% 
          select(-c("a", "A","B","C"))                  #drop variables that don't give necessary info
```

Make spaghetti plot for observation data 
```{r}
patient_data_clean %>% 
  ggplot(aes(x = week, y = observation, group = arm, color = arm)) +
  geom_point(size = 2, alpha = 0.5) + 
  geom_path(alpha = 0.7) + 
  labs(
    title = "Data on each subject in control and experimental arm \noberseved over 8 weeks",
    y = "Observation (value)", 
    x= "Week") +
  viridis::scale_color_viridis(
    discrete = TRUE) + 
  theme_bw() +
  theme(legend.position = "bottom",
        plot.title = element_text(
          hjust = 0.5, size=12, face='bold'))
```

